### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by Shunya078** [takurinton/old-blog.takurinton.dev#10]
https://github.com/takurinton/wip.blog.takurinton.dev/blob/main/client/components/Typography/TypographyWrapper.tsx#L12

`nomal` -> `normal`

~boldもあった方が汎用性上がりそう 👀~ -> あった

**Comment by takurinton** [comment]
@Shunya078 
ありがとうございます（1箇所間違えるとその先補完とコピペで永遠に間違えてしまうやつ）
